---
title: "Statistical Inference Project"
author: "arturop@gmail.com"
output: html_document
---
## Overview
This report addresses, via simulation, how representative the mean and the variance of the respective means of a series of samples of an exponential distribution (estimators) are of the mean and the variance of the population.

### Simulations
The following code describes, annotated by comments, how I simulated 1000 samples with 40 observations from an exponential distribution each, how I represented the main questions I wanted to explore via a chart and also puts the different estimands and estimators side by side to see how close they come. The chart also compares how close the distribution is to a normal one depicted in purple and overlaid on the distribution of the samples. 

```{r, fig.width=9, fig.height = 6, fig.align='center', warning=FALSE}
library(ggplot2)

#fix seed to guarantee reproduceability
set.seed(272727)

#parameters for the simulation
lambda <- 0.2
nosim <- 1000
n <- 40

#derive stats for the exponential distribution
popMean <- 1/lambda
popVariance <- (1/lambda)^2

#construct a matrix with 1000 rows with 40 samples each from the exp distribution
table <- matrix(rexp(n*nosim, lambda), nrow = nosim) #40*1000 elements laid out in 1000 rows, 40 elements per row
dat <- data.frame(
  #I take the mean for each of the rows and put it in x
  x = apply(table, 1, mean))

sampleMean <- mean(dat$x)
sampleVariance <- var(dat$x)

#histogram of the simulation
g <- ggplot(dat, aes(x = x)) + geom_histogram(alpha = .20, binwidth=.2, colour = "black", aes(y = ..density..))

#overlay the expected mean in green and the sample mean in red
g <- g + geom_vline(aes(xintercept = popMean, color="Theoretical Mean"), size = 2, show_guide = TRUE) +
  geom_vline(aes(xintercept = sampleMean, color="Actual Mean"), size = 1.2, show_guide = TRUE) +
  scale_colour_manual(name = "Means", values=c("red","green"))

#overlay the corresponding normal distribution
g <- g + stat_function(fun = dnorm, arg = c(mean = sampleMean, sd = sqrt(sampleVariance)), color = "purple")
g
```
Note: I made the line representing the theoretical mean thicker than the other one. This is a representation trick which I found useful as it shows how the latter is fully contained in the former. If left to the same size they became undistinguishable

#### Comparison of means and variances

- Population Mean (in green) `r popMean`
- Sample Mean (in red) `r sampleMean`
- Population variance `r popVariance`
- Estimate of variance  `popVariance / n` = `r popVariance / n`
- Sample variance `r sampleVariance`
